blank_issues_enabled: true

contact_links:
  - name: Documentation
    url: https://github.com/JulesGrillot/plugin_bd_topo_extractor
    about: Please read carefully the documentation before to submit an issue.
